package manif_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/tarantool/go-luarocks/manif"
)

// TestWriteByteEqual drives the canonical byte-equality regression.
//
// For every input under testdata/persist/in/*.lua there must be a partner
// golden under testdata/persist/out/<name>.out generated by upstream
// persist.lua (see gen_goldens.sh). We Parse the input (a `return { ... }`
// Lua source), feed the parsed value to Write, and demand byte equality
// with the golden.
//
// Parser bugs that lose data would corrupt the input side and produce a
// false GREEN — the parser round-trip tests in parser_test.go guard
// against that independently.
func TestWriteByteEqual(t *testing.T) {
	t.Parallel()

	inputs, err := filepath.Glob(filepath.Join("testdata", "persist", "in", "*.lua"))
	require.NoError(t, err, "glob inputs")
	require.NotEmpty(t, inputs, "no inputs in testdata/persist/in/*.lua — run manif/gen_goldens.sh")

	for _, in := range inputs {
		name := strings.TrimSuffix(filepath.Base(in), ".lua")
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			rawIn, err := os.ReadFile(in) //nolint:gosec // input path from a controlled testdata glob
			require.NoError(t, err, "read input")

			rawIn = stripReturnPrefix(rawIn)
			parsed, err := manif.Parse(rawIn)
			require.NoError(t, err, "parse input")

			top, ok := parsed.(map[string]any)
			require.True(t, ok, "Parse returned %T, want map", parsed)
			inner, ok := top["__root__"]
			require.True(t, ok, "Parse output missing __root__ wrapper")

			var buf bytes.Buffer

			require.NoError(t, manif.Write(&buf, inner), "Write")

			goldenPath := filepath.Join("testdata", "persist", "out", name+".out")
			golden, err := os.ReadFile(goldenPath) //nolint:gosec // golden path derived from a controlled testdata glob
			require.NoError(t, err, "read golden %s", goldenPath)
			assert.Equal(t, golden, buf.Bytes(), "byte mismatch")
		})
	}
}

// stripReturnPrefix turns a `return { ... }` source (the input corpus
// shape) into a parseable assignments-mode source by wrapping it in a
// synthetic single key `__root__ = ...`. We then unwrap.
//
// Inputs in testdata/persist/in/*.lua are `return T` files because that is
// what Lua's loadstring is happy with for free-standing table literals.
// The Go Parse function only accepts assignments-mode; this helper bridges
// the two without us needing a second parser variant.
func stripReturnPrefix(src []byte) []byte {
	s := strings.TrimSpace(string(src))
	if after, ok := strings.CutPrefix(s, "return "); ok {
		s = "__root__ = " + after
	} else if after, ok := strings.CutPrefix(s, "return\n"); ok {
		s = "__root__ = " + after
	}

	return []byte(s)
}
